### ISSUE TITLE
ChatGPT 客户端支持情况展示

### ISSUE THREAD

**Issue by zuisong** [zuisong/gemini-openai-proxy#7]
实测支持以下客户端（更多客户端欢迎补充）：
- [x] https://github.com/sigoden/aichat
- [x] https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web
- [x] https://github.com/josStorer/chatGPTBox
- [x] [gitlens](https://github.com/gitkraken/vscode-gitlens#automatically-generate-commit-message) 自动生成提交信息
- [x] [chatx](https://apps.apple.com/cn/app/chatx-ai-%E5%AE%9E%E7%94%A8%E5%B7%A5%E5%85%B7/id6446304087)

**Comment by yefx** [comment]
> 在nextweb中消息会被截断，我是用oneapi转发的= =

请问一下oneapi中如何设置呢？ 我设置上都会报错

**Comment by emengweb** [comment]
似乎一些包含代码的处理中，换行符\n没有没正确处理，导致代码未正确换行，看输出似乎是只有\缺少了n导致。这个问题具有随机性，在chatgpt-web中可以随机复现

**Comment by musuiot** [comment]
应该加上embedding模型的相关内容，否则在flowise中无法使用。

**Comment by azicen** [comment]
[lobe-chat](https://github.com/lobehub/lobe-chat)可以使用oneapi转发的接口

**Comment by manjieqi** [comment]
反馈一个uTools的插件---ChatGPT.好友，能够使用，但是有两个问题。

首先，输出回答的时候，插件是在内容全部生成完了，然后一次输出的。因为ChatGPT.好友是兼容OpenAI的流式输出的，所以是不是转写的时候格式和OpenAI的不一样。因为另外一个客户端ChatGPT Next Web它自己就支持Gemini，我看它的流式是正常的。

第二个问题，回答里面会夹着特殊字符，我在ChatGPT Next Web也重复试了同一个问题，没有出现。

<img width="500" alt="Snipaste_2024-06-09_12-55-42" src="https://github.com/zuisong/gemini-openai-proxy/assets/40858189/953b2a6e-1c2d-4ade-a92c-cf3bfcb1bcb1">

**Comment by zuisong** [comment]
@manjieqi  感谢反馈。
第一个问题，为了适配`function call`, 目前gemini调用的是不是流式借口，中间转发的时候适配了 openai 的流式相应格式， 所以客户端可以以流式的调用方式获得相应，只是会最终一起得到结果，**暂时没有修改的计划**。

第二个问题， 目前我没有复现这个问题，可能gemini响应本身就是乱码的。

**Comment by manjieqi** [comment]
对编程不是很懂啊，我理解function call就是在请求体里面加了字段，客户端请求里面没有相关字段，转换格式的时候也会另外设置吧，这样这部分不是可以使用gemini流式？

**Comment by skywk** [comment]
> 实测支持以下客户端（更多客户端欢迎补充）：
> 
> * [x]  https://github.com/sigoden/aichat[x]  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web[x]  https://github.com/josStorer/chatGPTBox[x]  [gitlens](https://github.com/gitkraken/vscode-gitlens#automatically-generate-commit-message) 自动生成提交信息[x]  [chatx](https://apps.apple.com/cn/app/chatx-ai-%E5%AE%9E%E7%94%A8%E5%B7%A5%E5%85%B7/id6446304087)

aichat要怎样配置？
我的配置如下：

model: Google
clients:
- type: openai-compatible
  name: Google
  api_base: xxx
  api_key: xxx
  models:
  - name: gpt-4-turbo
  
其中xxx处删除了真实地址和key，但报错：

Error: Failed to call chat-completions api

Caused by:
    Invalid response data: Page Not Found (status: 404)

在NextChat中可以正常使用

**Comment by zuisong** [comment]
@skywk  可以这样配置
```yml
  - #
    name: deno.dev-gemini-openai-proxy
    type: openai-compatible
    api_base: https://gemini-openai-proxy.deno.dev/v1
    api_key: xxxxxxx
    models:
      - name: gpt-3.5-turbo
      - name: gpt-4
      - name: gpt-4o
      - name: gemini-1.5-flash
      - name: gemini-2.0-flash
```
